spring.application.name=order-service
spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=76c20d7f8d88b1
spring.mail.password=8794b14be4b8e9
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
